[package]
name = "cloud_os"
version = "0.1.0"
authors = ["Edwin Cloud <ecloud412@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.8.0"
